package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellido;
     private String ciudad;
     private Set ventases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String dni) {
        this.dni = dni;
    }
    public Clientes(String dni, String nombre, String apellido, String ciudad, Set ventases) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ciudad = ciudad;
       this.ventases = ventases;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


