package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private String codcoche;
     private String nombre;
     private String modelo;
     private Set marcos = new HashSet(0);
     private Set ventases = new HashSet(0);
     private Set distribucions = new HashSet(0);

    public Coches() {
    }

	
    public Coches(String codcoche) {
        this.codcoche = codcoche;
    }
    public Coches(String codcoche, String nombre, String modelo, Set marcos, Set ventases, Set distribucions) {
       this.codcoche = codcoche;
       this.nombre = nombre;
       this.modelo = modelo;
       this.marcos = marcos;
       this.ventases = ventases;
       this.distribucions = distribucions;
    }
   
    public String getCodcoche() {
        return this.codcoche;
    }
    
    public void setCodcoche(String codcoche) {
        this.codcoche = codcoche;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set getMarcos() {
        return this.marcos;
    }
    
    public void setMarcos(Set marcos) {
        this.marcos = marcos;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    public Set getDistribucions() {
        return this.distribucions;
    }
    
    public void setDistribucions(Set distribucions) {
        this.distribucions = distribucions;
    }




}


