package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concesionarios generated by hbm2java
 */
public class Concesionarios  implements java.io.Serializable {


     private String cifc;
     private String nombre;
     private String ciudad;
     private Set distribucions = new HashSet(0);
     private Set ventases = new HashSet(0);

    public Concesionarios() {
    }

	
    public Concesionarios(String cifc) {
        this.cifc = cifc;
    }
    public Concesionarios(String cifc, String nombre, String ciudad, Set distribucions, Set ventases) {
       this.cifc = cifc;
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.distribucions = distribucions;
       this.ventases = ventases;
    }
   
    public String getCifc() {
        return this.cifc;
    }
    
    public void setCifc(String cifc) {
        this.cifc = cifc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getDistribucions() {
        return this.distribucions;
    }
    
    public void setDistribucions(Set distribucions) {
        this.distribucions = distribucions;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


