package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1



/**
 * Distribucion generated by hbm2java
 */
public class Distribucion  implements java.io.Serializable {


     private DistribucionId id;
     private Coches coches;
     private Concesionarios concesionarios;
     private Integer cantidad;

    public Distribucion() {
    }

	
    public Distribucion(DistribucionId id, Coches coches, Concesionarios concesionarios) {
        this.id = id;
        this.coches = coches;
        this.concesionarios = concesionarios;
    }
    public Distribucion(DistribucionId id, Coches coches, Concesionarios concesionarios, Integer cantidad) {
       this.id = id;
       this.coches = coches;
       this.concesionarios = concesionarios;
       this.cantidad = cantidad;
    }
   
    public DistribucionId getId() {
        return this.id;
    }
    
    public void setId(DistribucionId id) {
        this.id = id;
    }
    public Coches getCoches() {
        return this.coches;
    }
    
    public void setCoches(Coches coches) {
        this.coches = coches;
    }
    public Concesionarios getConcesionarios() {
        return this.concesionarios;
    }
    
    public void setConcesionarios(Concesionarios concesionarios) {
        this.concesionarios = concesionarios;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


