package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private String cifm;
     private String nombre;
     private String ciudad;
     private Set marcos = new HashSet(0);

    public Marcas() {
    }

	
    public Marcas(String cifm) {
        this.cifm = cifm;
    }
    public Marcas(String cifm, String nombre, String ciudad, Set marcos) {
       this.cifm = cifm;
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.marcos = marcos;
    }
   
    public String getCifm() {
        return this.cifm;
    }
    
    public void setCifm(String cifm) {
        this.cifm = cifm;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getMarcos() {
        return this.marcos;
    }
    
    public void setMarcos(Set marcos) {
        this.marcos = marcos;
    }




}


