package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1



/**
 * Marco generated by hbm2java
 */
public class Marco  implements java.io.Serializable {


     private MarcoId id;
     private Coches coches;
     private Marcas marcas;
     private Integer descuento;

    public Marco() {
    }

	
    public Marco(MarcoId id, Coches coches, Marcas marcas) {
        this.id = id;
        this.coches = coches;
        this.marcas = marcas;
    }
    public Marco(MarcoId id, Coches coches, Marcas marcas, Integer descuento) {
       this.id = id;
       this.coches = coches;
       this.marcas = marcas;
       this.descuento = descuento;
    }
   
    public MarcoId getId() {
        return this.id;
    }
    
    public void setId(MarcoId id) {
        this.id = id;
    }
    public Coches getCoches() {
        return this.coches;
    }
    
    public void setCoches(Coches coches) {
        this.coches = coches;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }




}


