package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1



/**
 * MarcoId generated by hbm2java
 */
public class MarcoId  implements java.io.Serializable {


     private String cifm;
     private String codcoche;

    public MarcoId() {
    }

    public MarcoId(String cifm, String codcoche) {
       this.cifm = cifm;
       this.codcoche = codcoche;
    }
   
    public String getCifm() {
        return this.cifm;
    }
    
    public void setCifm(String cifm) {
        this.cifm = cifm;
    }
    public String getCodcoche() {
        return this.codcoche;
    }
    
    public void setCodcoche(String codcoche) {
        this.codcoche = codcoche;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarcoId) ) return false;
		 MarcoId castOther = ( MarcoId ) other; 
         
		 return ( (this.getCifm()==castOther.getCifm()) || ( this.getCifm()!=null && castOther.getCifm()!=null && this.getCifm().equals(castOther.getCifm()) ) )
 && ( (this.getCodcoche()==castOther.getCodcoche()) || ( this.getCodcoche()!=null && castOther.getCodcoche()!=null && this.getCodcoche().equals(castOther.getCodcoche()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCifm() == null ? 0 : this.getCifm().hashCode() );
         result = 37 * result + ( getCodcoche() == null ? 0 : this.getCodcoche().hashCode() );
         return result;
   }   


}


