package es.munvi.hibernateconfig;
// Generated 13-sep-2015 13:03:19 by Hibernate Tools 4.3.1



/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private VentasId id;
     private Clientes clientes;
     private Coches coches;
     private Concesionarios concesionarios;
     private String color;

    public Ventas() {
    }

	
    public Ventas(VentasId id, Clientes clientes, Coches coches, Concesionarios concesionarios) {
        this.id = id;
        this.clientes = clientes;
        this.coches = coches;
        this.concesionarios = concesionarios;
    }
    public Ventas(VentasId id, Clientes clientes, Coches coches, Concesionarios concesionarios, String color) {
       this.id = id;
       this.clientes = clientes;
       this.coches = coches;
       this.concesionarios = concesionarios;
       this.color = color;
    }
   
    public VentasId getId() {
        return this.id;
    }
    
    public void setId(VentasId id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Coches getCoches() {
        return this.coches;
    }
    
    public void setCoches(Coches coches) {
        this.coches = coches;
    }
    public Concesionarios getConcesionarios() {
        return this.concesionarios;
    }
    
    public void setConcesionarios(Concesionarios concesionarios) {
        this.concesionarios = concesionarios;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


